name: linkedmeet-frontend

services:
  app:
    container_name: "frontend-app"
    image: node:lts-alpine
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /app
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      APP_ENV: ${APP_ENV}
    mem_limit: 1G
    cpus: 1
    networks:
      - linkedmeet
  npm:
    container_name: "frontend-npm"
    image: node:lts-alpine
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ 'npm' ]
    profiles:
      - tools
    networks:
      - linkedmeet

networks:
  linkedmeet:
    driver: bridge
    external: true