name: linkedmeet-frontend

services:
  app:
    container_name: "frontend-app"
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
    image: linkedmeet-node:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      APP_ENV: ${APP_ENV}
    networks:
      - linkedmeet
  npm:
    container_name: "frontend-npm"
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
    image: linkedmeet-node:latest
    volumes:
      - .:/app
    entrypoint: [ 'npm' ]
    profiles:
      - tools
    networks:
      - linkedmeet

networks:
  linkedmeet:
    driver: bridge
    external: true
